#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

create_workspace_bracket_for_monitor() {
  parameters=("$@")                              # all function arguments
  monitor_id=${parameters[0]}                    # first argument is monitor ID 
  monitor_workspaces=("${parameters[@]:1}")      # all other arguments are workspace IDs

  # for every workspace in the monitor, create an item that represents it
  for workspace_id in ${monitor_workspaces[@]}; do
    sketchybar --add item  workspaces."$monitor_id"."$workspace_id" left \
                          --subscribe workspaces."$monitor_id"."$workspace_id" aerospace_workspace_change \
                          --set       workspaces."$monitor_id"."$workspace_id" \
                                      background.drawing=off \
                                      background.height=10 \
                                      background.padding_left=10 \
                                      background.padding_right=10 \
                                      click_script="aerospace workspace $workspace_id" \
                                      label="$workspace_id" \
                                      label.width=5\
                                      label.padding_left=1 \
                                      label.padding_right=1\
                                      label.y_offset=1 \
                                      script="$PLUGIN_DIR/aerospace $workspace_id"
  done

  # add separate bar if we're not drawing items for the last monitor
  if [ $monitor_id -lt ${#monitor_ids[@]} ]; then
    sketchybar --add item workspaces_monitor_separator."$monitor_id" left \
               --set      workspaces_monitor_separator."$monitor_id" \
                          background.drawing=off \
                          background.padding_left=0 \
                          background.padding_right=0 \
                          label.padding_left=0 \
                          label.width=104 \
                          label.font.size="$BACKGROUND_HEIGHT" \
                          label="───────"
  else
    # if it is the last monitor then add in indicator for service mode
    sketchybar --add item workspaces_service_mode left \
           --subscribe workspaces_service_mode aerospace_service_mode_enabled_changed \
           --set       workspaces_service_mode \
                       background.drawing=on \
                                      background.padding_left=10 \
                                      background.padding_right=10 \
                       label.drawing=off \
                       label.highlight=on \
                       label.font="$LABEL_HIGHLIGHT_FONT" \
                       label="[s]" \
                       label.padding_right=10 \
                       script="$PLUGIN_DIR/aerospace $AEROSPACE_SERVICE_MODE_ENABLED"
  fi
}

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_service_mode_enabled_changed

monitor_ids=( $(aerospace list-monitors | awk '{print $1}') )

# TODO:
# - Update this view when moving workspaces to a different monitors.
# - Only show workspaces with active windows or currently selected like in i3
#   default configuration.

# for each monitor, create the items that represent the workspaces in each. If it's not 
# the last monitor, add a separator between the workspaces of the current monitor and the next
for monitor_id in ${monitor_ids[@]}; do
  workspaces_for_monitor_id=( $(aerospace list-workspaces --monitor $monitor_id) )
  create_workspace_bracket_for_monitor $monitor_id "${workspaces_for_monitor_id[@]}"
done

