#!/usr/bin/env bash
source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

CLOCK_LABEL_COLOR="$magenta"
CLOCK_BACKGROUND_BORDER_COLOR="$magenta"

sketchybar --add item time right \
           --set      time \
                      background.drawing=off \
                      padding_right=30 \
                      padding_left=10 \
                      label.color="$CLOCK_LABEL_COLOR" \
                      label.padding_left=0 \
                      label.padding_right=0 \
                      update_freq=10 \
                      script="$PLUGIN_DIR/time"

sketchybar --add item clock right \
           --set      clock \
                      background.drawing=off \
                      padding_left=10 \
                      label.color="$CLOCK_LABEL_COLOR" \
                      label.padding_left=0 \
                      label.padding_right=0 \
                      update_freq=10 \
                      script="$PLUGIN_DIR/clock"


sketchybar --add item volume right \
           --set      volume \
                      background.drawing=off \
                      padding_left=10 \
                      label.color="$CLOCK_LABEL_COLOR" \
                      label.padding_left=4 \
                      label.padding_right=4 \
                      script="$PLUGIN_DIR/volume" \
                      icon.font="Hack Nerd Font:Bold:17.0" \
                      icon.padding_left=4 \
                      icon.padding_right=4 \
                      icon.drawing=on \
                      icon.color="$CLOCK_LABEL_COLOR" \
                      icon="" \
           --subscribe volume volume_change 

sketchybar --add item battery right \
           --set      battery \
                      background.drawing=off \
                      label.color="$CLOCK_LABEL_COLOR" \
                      label.padding_left=0 \
                      label.padding_right=0 \
                      update_freq=120 \
                      script="$PLUGIN_DIR/battery" \
                      icon.font="Hack Nerd Font:Bold:17.0" \
                      icon.padding_left=4 \
                      icon.padding_right=4 \
                      icon.drawing=on \
                      icon.color="$CLOCK_LABEL_COLOR" \
                      icon="" \
           --subscribe battery system_woke power_source_change

